/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-platform`
    `maven-publish`
}

group = "jp.co.sony.csl.dcoes.apis"
version = "3.9.14"
description = "APIS BOM"

dependencies {
    constraints {
        api(libs.io.vertx.vertx.core)
        api(libs.io.vertx.vertx.mongo.client)
        api(libs.io.vertx.vertx.hazelcast)
        api(libs.io.vertx.vertx.unit)
        
        api(libs.junit.junit)
        api(libs.commons.io.commons.io)
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["javaPlatform"])
        }
    }
}